### ISSUE TITLE
Master shuts down with out of memory

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1127]
[Story](https://www.pivotaltracker.com/story/show/98513158)
in kafka-hdfs-pipeline example master will exit the JVM. Log out follows...

**Comment by kkasravi** [comment]
Below is the log
```
2015-07-06 19:51:06,434 INFO Master$: Starting Master Actor system ip-10-10-10-33.us-west-2.compute.internal:3000, master list: ip-10-10-10-33.us-west-2.compute.internal:3000
2015-07-06 19:51:06,736 INFO Slf4jLogger: Slf4jLogger started
2015-07-06 19:51:06,848 INFO Remoting: Starting remoting
2015-07-06 19:51:07,044 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000]
2015-07-06 19:51:07,062 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Starting up...
2015-07-06 19:51:07,132 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Registered cluster JMX MBean [akka:type=Cluster]
2015-07-06 19:51:07,133 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Started up successfully
2015-07-06 19:51:07,138 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Metrics will be retreived from MBeans, and may be incorrect on some platforms. To increase metric accuracy add the 'sigar.jar' to the classpath and the appropriate platform-specific native libary to 'java.library.path'. Reason: java.lang.ClassNotFoundException: org.hyperic.sigar.Sigar
2015-07-06 19:51:07,140 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Metrics collection has started successfully
2015-07-06 19:51:07,153 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] is JOINING, roles [master]
2015-07-06 19:51:07,180 INFO Metrics$: Metrics is enabled...,  true
2015-07-06 19:51:07,182 INFO Metrics$: Metrics reporter is enabled, using akka reporter
2015-07-06 19:51:07,199 INFO Master$: Replicator path: akka://master/user/replicator
2015-07-06 19:51:07,210 INFO Master$: master proxy is started at akka://master/user/master
2015-07-06 19:51:08,146 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Leader is moving node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] to [Up]
2015-07-06 19:51:08,152 INFO ClusterSingletonManager: Singleton manager [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] starting singleton actor
2015-07-06 19:51:08,153 INFO ClusterSingletonManager: ClusterSingletonManager state change [Start -> Oldest]
2015-07-06 19:51:08,156 INFO Master: master is started at akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000/user/singleton/masterwatcher/master...
2015-07-06 19:51:08,162 INFO Master: master path is akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000/user/singleton/masterwatcher/master
2015-07-06 19:51:08,174 INFO MasterHAService: cannot find any master state
2015-07-06 19:51:08,175 INFO AppManager: Application Manager started. Ready for application submission...
2015-07-06 19:51:08,903 INFO HttpListener: Bound to ip-10-10-10-33.us-west-2.compute.internal/10.10.10.33:0
2015-07-06 19:51:08,904 INFO FileServer: retunning port: 51174
2015-07-06 19:51:09,150 INFO ClusterSingletonProxy: Singleton identified: akka://master/user/singleton/masterwatcher/master
2015-07-06 19:51:09,155 INFO PriorityScheduler: Worker 1258395558 added to the scheduler
2015-07-06 19:51:09,156 INFO Master: Register Worker 1258395558 from ip-10-10-10-40.us-west-2.compute.internal ....
2015-07-06 19:51:09,156 INFO PriorityScheduler: Worker 256654109 added to the scheduler
2015-07-06 19:51:09,156 INFO Master: Register Worker 256654109 from ip-10-10-10-217.us-west-2.compute.internal ....
2015-07-06 19:51:09,177 INFO PriorityScheduler: Resource update id: 1258395558, slots: 1000....
2015-07-06 19:51:09,180 INFO PriorityScheduler: Resource update id: 256654109, slots: 1000....
2015-07-06 19:54:41,100 INFO AppManager: AppManager Submitting Application 1...
2015-07-06 19:54:41,102 INFO AppMasterLauncher@app1: AppManager asking Master for resource for app 1...
2015-07-06 19:54:41,106 INFO PriorityScheduler: Request resource: appId: 1, slots: 1, relaxation: ANY
2015-07-06 19:54:41,258 INFO AppMasterLauncher@app1: Resource allocated for appMaster 1
2015-07-06 19:54:41,261 INFO AppMasterLauncher@app1: Try to launch a executor for app Master on Actor[akka.tcp://29537b31-1325-4d71-bb6d-5e0c9f10bf62@ip-10-10-10-40.us-west-2.compute.internal:32972/user/Worker29537b31-1325-4d71-bb6d-5e0c9f10bf62#-1868690034] for app 1
2015-07-06 19:54:41,314 INFO PriorityScheduler: Resource update id: 1258395558, slots: 999....
2015-07-06 19:54:43,574 INFO AppMasterLauncher@app1: Received RegisterActorSystem akka.tcp://app1-executor-1@ip-10-10-10-40.us-west-2.compute.internal:45303 for app master
2015-07-06 19:54:43,688 INFO AppMasterLauncher@app1: AppMaster is created, stopping myself...
2015-07-06 19:54:43,728 INFO AppManager: Register AppMaster for app: 1 AppMasterRuntimeInfo(1,test12_KafkaHdfsPipeLine,Actor[akka.tcp://29537b31-1325-4d71-bb6d-5e0c9f10bf62@ip-10-10-10-40.us-west-2.compute.internal:32972/user/Worker29537b31-1325-4d71-bb6d-5e0c9f10bf62#-1868690034],ec2-user,1436226881258,1436226883726,0,Config(SimpleConfigObject({"gearpump":{"app":{"jar":"output/target/pack/examples/gearpump-examples-kafka-hdfs-pipeline-assembly-0.3.8-SNAPSHOT.jar","name":{"prefix":"test12"}},"appmaster":{"extraClasspath":"","vmargs":"-server -Xms512M -Xmx1024M -Xss1M -XX:MaxPermSize=128m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+UseParNewGC -XX:NewRatio=3"},"cluster":{"masters":{"0":"ip-10-10-10-33.us-west-2.compute.internal:3000"}},"executor":{"extraClasspath":"","vmargs":"-server -Xms512M -Xmx1024M -Xss1M -XX:MaxPermSize=128m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+UseParNewGC -XX:NewRatio=3"},"hostname":"ip-10-10-10-236","log":{"application":{"dir":"logs"},"daemon":{"dir":"logs"}},"metrics":{"enabled":true,"graphite":{"host":"127.0.0.1","port":2003},"logfile":{},"report-interval-ms":3000,"reporter":"akka","sample-rate":10},"netty":{"base-sleep-ms":100,"buffer-size":5242880,"flush-check-interval":5,"max-retries":30,"max-sleep-ms":1000,"message-batch-size":262144},"remote-debug-executor-jvm":false,"resource-allocation-timeout-seconds":120,"scheduling":{"scheduler-class":"org.apache.gearpump.cluster.scheduler.PriorityScheduler"},"serializers":{"org.apache.gearpump.experiments.pipeline.SpaceShuttleRecord":""},"services":{"host":"0.0.0.0","http":8090,"ws":8091},"task-dispatcher":{"fork-join-executor":{"parallelism-factor":2,"parallelism-max":8,"parallelism-min":2},"mailbox-type":"akka.dispatch.SingleConsumerOnlyUnboundedMailbox","throughput":100},"worker":{"slots":1000}},"kafka":{"consumer":{"client":{"id":"kafka-hdfs-pipeline-app"},"emit":{"batch":{"size":100}},"fetch":{"message":{"max":{"bytes":1048576}},"sleep":{"ms":100},"threshold":5000},"socket":{"receive":{"buffer":{"bytes":65536}},"timeout":{"ms":30000}},"topics":"javour-topic","zookeeper":{"connect":"10.10.10.46:2181,10.10.10.236:2181,10.10.10.164:2181/kafka"}},"grouper":{"factory":{"class":"org.apache.gearpump.streaming.kafka.lib.grouper.KafkaDefaultGrouperFactory"}},"producer":{"acks":"1","batch":{"size":16384},"bootstrap":{"servers":"10.10.10.46:9092,10.10.10.164:9092,10.10.10.236:9092"},"buffer":{"memory":33554432},"compression":{"type":"none"},"retries":0,"topic":"javour-topic"},"storage":{"replicas":1},"task":{"message":{"decoder":{"class":"org.apache.gearpump.streaming.kafka.lib.DefaultMessageDecoder"}},"timestamp":{"filter":{"class":"org.apache.gearpump.streaming.kafka.lib.KafkaFilter"}}}}})))
2015-07-06 19:54:43,852 INFO InMemoryKVService: We cannot find any kv
2015-07-06 19:54:43,919 INFO PriorityScheduler: Request resource: appId: 1, slots: 4, relaxation: ANY
2015-07-06 19:54:43,980 INFO PriorityScheduler: Resource update id: 1258395558, slots: 997....
2015-07-06 19:54:44,038 INFO PriorityScheduler: Resource update id: 256654109, slots: 998....
2015-07-06 19:54:44,052 INFO Master:  disassociated akka.tcp://client290196978@ip-10-10-10-236:36946
2015-07-06 19:54:44,055 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://client290196978@ip-10-10-10-236:36946] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
2015-07-06 19:54:44,060 INFO Master:  disassociated akka.tcp://client290196978@ip-10-10-10-236:36946
2015-07-06 19:54:44,490 INFO Master$: Triggering shutdown hook....
2015-07-06 19:54:44,491 ERROR ActorSystemImpl: Uncaught error from thread [master-akka.actor.default-dispatcher-12] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
	at java.lang.Object.clone(Native Method)
	at akka.util.CompactByteString$.apply(ByteString.scala:410)
	at akka.util.ByteString$.apply(ByteString.scala:22)
	at spray.http.HttpData$.apply(HttpData.scala:148)
	at spray.http.HttpEntity$.apply(HttpEntity.scala:37)
	at org.apache.gearpump.util.FileServer$$anonfun$listen$1.applyOrElse(FileServer.scala:80)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.gearpump.util.FileServer.aroundReceive(FileServer.scala:40)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2015-07-06 19:54:44,493 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Marked address [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] as [Leaving]
2015-07-06 19:54:44,494 INFO Cluster(akka://master): Cluster Node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] - Marking node [akka.tcp://master@ip-10-10-10-33.us-west-2.compute.internal:3000] as [Down]
2015-07-06 19:54:47,502 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
2015-07-06 19:54:47,504 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
2015-07-06 19:54:47,544 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
```

**Comment by kkasravi** [comment]
Size of jar file may have some bearing
```
[ec2-user@ip-10-10-10-236 gearpump]$ ls -l output/target/pack/examples/
total 85088
-rw-rw-r--. 1 ec2-user ec2-user    61557 Jul  6 19:46 gearpump-examples-complexdag-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user    38340 Jul  6 19:46 gearpump-examples-distributedshell-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user 22015585 Jul  6 19:46 gearpump-examples-fsio-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user    58473 Jul  6 19:46 gearpump-examples-kafka-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user 61868458 Jul  6 19:47 gearpump-examples-kafka-hdfs-pipeline-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user    18970 Jul  6 19:46 gearpump-examples-sol-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user  2598229 Jul  6 19:46 gearpump-examples-stockcrawler-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user   428438 Jul  6 19:46 gearpump-examples-transport-assembly-0.3.8-SNAPSHOT.jar
-rw-rw-r--. 1 ec2-user ec2-user    19378 Jul  6 19:46 gearpump-examples-wordcount-assembly-0.3.8-SNAPSHOT.jar
```

**Comment by clockfly** [comment]
fixed .
