### ISSUE TITLE
cannot deserialize guava ImmutableList

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1378]
The default kryo `CollectionSerializer` uses `add` which throws `UnsupportedOperationException` for guava ImmutableList.

```
[ERROR] [08/27/2015 06:32:56.696] [OneForOneStrategy] java.lang.UnsupportedOperationException 
   599 Serialization trace: 
   600 fields (storm.starter.tools.RankableObjectWithFields) 
   601 rankedItems (storm.starter.tools.Rankings) 
   602 tuple (io.gearpump.experiments.storm.util.StormTuple) 
   603 io.gearpump.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException 
   604 Serialization trace: 
   605 fields (storm.starter.tools.RankableObjectWithFields) 
   606 rankedItems (storm.starter.tools.Rankings) 
   607 tuple (io.gearpump.experiments.storm.util.StormTuple) 
   608         at io.gearpump.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) 
   609         at io.gearpump.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
   610         at io.gearpump.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764) 
   611         at io.gearpump.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:116) 
   612         at io.gearpump.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:22) 
   613         at io.gearpump.esotericsoftware.kryo.Kryo.readObject(Kryo.java:682) 
   614         at io.gearpump.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
   615         at io.gearpump.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
   616         at io.gearpump.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764) 
   617         at io.gearpump.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:45) 
   618         at io.gearpump.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:36) 
   619         at io.gearpump.esotericsoftware.kryo.Kryo.readObject(Kryo.java:682) 
   620         at io.gearpump.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
   621         at io.gearpump.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
   622         at io.gearpump.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764) 
   623         at io.gearpump.streaming.MessageSerializer.read(MessageSerializer.scala:34) 
   624         at io.gearpump.streaming.MessageSerializer.read(MessageSerializer.scala:26) 
   625         at io.gearpump.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764) 
   626         at io.gearpump.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:394) 
   627         at akka.serialization.Serializer$class.fromBinary(Serializer.scala:60) 
   628         at io.gearpump.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:368) 
   629         at io.gearpump.romix.serialization.kryo.KryoSerializerWrapper.fromBinary(KryoSerializerWrapper.java:41) 
   630         at io.gearpump.serializer.FastKryoSerializer.deserialize(FastKryoSerializer.scala:77)

It's not possible to import a kryo guava serializer library because we shade the `Serializer` class and a ClassCastException would be thrown.

**Comment by manuzhang** [comment]
@huafengw would you help to take a look ?

**Comment by huafengw** [comment]
So the problem is that we shaded kryo?

**Comment by manuzhang** [comment]
shading makes it impossible to use external kryo libraries 

```scala
   val register = kryo.register(keyClass, valueClass.newInstance().asInstanceOf[Serializer[_]])
```

with `Serializer` of the type `io.gearpump.esotericsoftware.kryo.Serializer`

**Comment by huafengw** [comment]
I think it's a potential issue because user can not use their external serializers in Gearpump

**Comment by manuzhang** [comment]
@huafengw opened #1387 for this
