### ISSUE TITLE
Randomly see AskTimeoutException while querying app status 

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1577]
While running integration test, I noticed an interesting thing. 

I query app status, it returns its current runtime information immediately (after 0.1 second). And then I sleep 1 second and query again. I met a `AskTimeoutException` after 15 seconds. Is there any internal resource locking cause this? For instance some property is being updated. During the updating, any app query request will be timed out? 

```
[DEBUG] [23:00:26.755] [Docker$] EXEC master0 => `docker exec master0 curl -s  http://master0:8090/api/v1.0/appmaster/12?detail=true`
[DEBUG] [23:00:26.856] [Docker$] EXEC master0 <= `{"appId":12,"appName":"wordCount","processors":[[1,{"id":1,"taskClass":"io.gearpump.streaming.examples.wordcount.Sum","parallelism":1,"description":"","taskConf":{"_config":{}},"life":{"birth":"0","death":"9223372036854775807"},"executors":[],"taskCount":[]}],[0,{"id":0,"taskClass":"io.gearpump.streaming.examples.wordcount.Split","parallelism":1,"description":"","taskConf":{"_config":{}},"life":{"birth":"0","death":"9223372036854775807"},"executors":[],"taskCount":[]}]],"processorLevels":[[0,0],[1,1]],"dag":{"vertexList":[0,1],"edgeList":[[0,"io.gearpump.partitioner.HashPartitioner",1]]},"actorPath":"akka.tcp://app12-executor-1@10.0.2.172:55106/user/daemon/appdaemon12/$c/appmaster","executors":[{"executorId":-1,"executor":"akka://app12-executor-1/user/daemon/appdaemon12/$c/appmaster","workerId":1,"status":"active"}],"startTime":"1448031626490","uptime":"348","user":"root","homeDirectory":"/opt/gearpump","logFile":"/opt/gearpump/logs"}` with exit code 0
[DEBUG] [23:00:27.857] [Docker$] EXEC master0 => `docker exec master0 curl -s  http://master0:8090/api/v1.0/appmaster/12?detail=true`
[DEBUG] [23:00:42.920] [Docker$] EXEC master0 <= `akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://app12-executor-1@10.0.2.172:55106/user/daemon/appdaemon12/$c#1633808116]] after [15000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)` with exit code 0
```

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-102
