### ISSUE TITLE
Error message should indicate the reason of application submission failure

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1668]
If a cluster has 1000 free slots, but an application required 1001 slots to start, the application will be failed to start. We should clearly show the reason in response, rather than parsing its log to find out the failure reason.

This suggestion is inspired by investigating #1499

**Comment by stanleyxu2005** [comment]
Here is an easy step to verify:
1. Start cluster without any worker
2. Submit a wordcount application
3. Check the error log.

According to the log, user is very hard to know, there is no resource available to launch the application.
```
java.io.IOException: Process exit abnormally with code 1 
[INFO] [12/21/2015 14:05:16.183] [ClusterConfig$] loading config file application.conf...
[INFO] [12/21/2015 14:05:16.310] [ClusterConfig$] loading config file application.conf...
[INFO] [12/21/2015 14:05:16.602] [Slf4jLogger] Slf4jLogger started
[INFO] [12/21/2015 14:05:16.685] [Remoting] Starting remoting
[INFO] [12/21/2015 14:05:16.843] [Remoting] Remoting started; listening on addresses :[akka.tcp://client1506396222@127.0.0.1:39588]
[INFO] [12/21/2015 14:05:16.873] [Metrics$] Metrics is enabled...,  true
[INFO] [12/21/2015 14:05:16.875] [ClientContext] Starting system client1506396222
[INFO] [12/21/2015 14:05:16.895] [MasterProxy@masterproxy841884180] Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
[INFO] [12/21/2015 14:05:16.898] [MasterProxy@masterproxy841884180] sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:3000/), Path(/user/master)]
[INFO] [12/21/2015 14:05:16.898] [MasterProxy@masterproxy841884180] Master Proxy is started...
[INFO] [12/21/2015 14:05:17.040] [MasterProxy@masterproxyclient1506396222] Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
	at io.gearpump.services.MasterService$.submitJar(MasterService.scala:224)
	at io.gearpump.services.MasterService$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$1.apply$mcI$sp(MasterService.scala:130)
	at io.gearpump.services.MasterService$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$1.apply(MasterService.scala:130)
	at io.gearpump.services.MasterService$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$1.apply(MasterService.scala:130)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by stanleyxu2005** [comment]
Add a reference to #1437

**Comment by kkasravi** [comment]
See [GEARPUMP-39](https://issues.apache.org/jira/browse/GEARPUMP-39)
