### ISSUE TITLE
Error log when launch YARN application master

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1731]
I notice there is a NPE in application log!

```
[INFO] [12/17/2015 11:38:41.857] [YarnApplicationMaster] warning already allocated ${container.getId}
[INFO] [12/17/2015 11:38:41.874] [YarnApplicationMaster] Started worker container : container_1_0001_01_000001
[INFO] [12/17/2015 11:38:41.885] [YarnApplicationMaster] Started worker container : container_1_0001_01_000001
[WARN] [12/17/2015 11:38:41.885] [YarnApplicationMaster] no allocated worker container found ${container.getId}
[INFO] [12/17/2015 11:38:41.900] [YarnApplicationMaster] Started worker container : container_1_0001_01_000001
[INFO] [12/17/2015 11:38:41.935] [YarnApplicationMaster] Starting services UI
[INFO] [12/17/2015 11:38:42.071] [YarnApplicationMaster] Application completed. ContainerStats(1,1,0,1)
[ERROR] [12/17/2015 11:38:41.990] [testsystem-akka.actor.default-dispatcher-3] [akka://testsystem/user/$$y/$a] null
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
	at akka.actor.ActorCell.create(ActorCell.scala:596)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:342)
	at scala.collection.mutable.ArrayOps$ofRef.addString(ArrayOps.scala:186)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:308)
	at scala.collection.mutable.ArrayOps$ofRef.mkString(ArrayOps.scala:186)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:310)
	at scala.collection.mutable.ArrayOps$ofRef.mkString(ArrayOps.scala:186)
	at io.gearpump.experiments.yarn.master.ServicesLauncherActor.preStart(ServicesLauncherActor.scala:30)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:472)
	at io.gearpump.experiments.yarn.master.ServicesLauncherActor.aroundPreStart(ServicesLauncherActor.scala:26)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	... 9 more
```
https://travis-ci.org/gearpump/gearpump?branch=master

**Comment by clockfly** [comment]
yarn is refactored.
