### ISSUE TITLE
yarnclient should support distribution package of either tar.gz or .zip or exit immediately

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1740]
Currently if the package argument specifies a tar.gz suffix the yarnclient will proceed to attempt to start the application master, print a help message (with exception) and then hang. Behavior should be a Usage message similar to what is shown now but no exception and then to cleanly exit. Supporting both tar.gz and .zip is preferred since this is what we did in the past as well as these are the types of packages we produce.

```
$ output/target/pack/bin/yarnclient launch -package /user/gearpump/gearpump-pack-2.11.5-0.7.1-SNAPSHOT.tar.gz -output /tmp/gp.conf
[INFO] [12/18/2015 19:19:57.941] [ClusterConfig$] loading config file application.conf...
[WARN] [12/18/2015 19:19:59.126] [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[WARN] [12/18/2015 19:19:59.152] [DomainSocketFactory] The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
[INFO] [12/18/2015 19:19:59.169] [RMProxy] Connecting to ResourceManager at cdh-master-0.node.demogotapaas.consul/10.10.10.146:8032
[INFO] [12/18/2015 19:19:59.292] [YarnClient] Starting YarnClient...
[INFO] [12/18/2015 19:19:59.620] [LaunchCluster] Starting AM

Help: 
-package (required:false, default:)<Please specify the gearpump.zip package path on HDFS. If not specified, we will use default value /user/gearpump/gearpump.zip>
-name (required:false, default:Gearpump)<Application name showed in YARN>
-verbose (required:false, default:false)<print verbose log on console>
-output (required:false, default:)<output path for configuration file>

Exception in thread "main" java.io.IOException: YarnClient only support .zip distribution package, now it is /user/gearpump/gearpump-pack-2.11.5-0.7.1-SNAPSHOT.tar.gz. Please download the zip package from website or use sbt assembly packArchiveZip to build one.
	at io.gearpump.experiments.yarn.client.LaunchCluster.submit(LaunchCluster.scala:68)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:186)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at scala.util.Try$.apply(Try.scala:191)
	at io.gearpump.util.AkkaApp$class.main(AkkaApp.scala:21)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:151)
	at io.gearpump.experiments.yarn.client.Client$.main(Client.scala:45)
	at io.gearpump.experiments.yarn.client.Client.main(Client.scala)
```

**Comment by clockfly** [comment]
@kkasravi,

An exception is desired compared with System.exit() you proposed, because the former one is more unit test friendly.
I don't see the hang issue you mentioned, the program throw an exception and exit as expected. 

```
[root@IDHV22-01 xzhong10]# /root/xzhong10/gearpump-pack-2.11.5-0.7.1-SNAPSHOT/bin/yarnclient launch -package /user/yarn/gearpump-pack-2.11.5-0.7.1-SNAPSHOT52.tar.gz
[INFO] [12/20/2015 16:35:40.692] [ClusterConfig$] loading config file application.conf...
[WARN] [12/20/2015 16:35:41.364] [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[INFO] [12/20/2015 16:35:42.044] [RMProxy] Connecting to ResourceManager at /0.0.0.0:8032
[INFO] [12/20/2015 16:35:42.159] [YarnClient] Starting YarnClient...
[INFO] [12/20/2015 16:35:42.495] [Slf4jLogger] Slf4jLogger started
[INFO] [12/20/2015 16:35:42.616] [Remoting] Starting remoting
[INFO] [12/20/2015 16:35:42.786] [Remoting] Remoting started; listening on addresses :[akka.tcp://launchCluster@127.0.0.1:58441]
[INFO] [12/20/2015 16:35:42.825] [Metrics$] Metrics is enabled...,  true
[INFO] [12/20/2015 16:35:42.834] [LaunchCluster] Starting AM

Help: 
-package (required:false, default:)<Please specify the gearpump.zip package path on HDFS. If not specified, we will use default value /user/gearpump/gearpump.zip>
-name (required:false, default:Gearpump)<Application name showed in YARN>
-verbose (required:false, default:false)<print verbose log on console>
-output (required:false, default:)<output path for configuration file>

Exception in thread "main" java.io.IOException: YarnClient only support .zip distribution package, now it is /user/yarn/gearpump-pack-2.11.5-0.7.1-SNAPSHOT52.tar.gz. Please download the zip package from website or use sbt assembly packArchiveZip to build one.
	at io.gearpump.experiments.yarn.client.LaunchCluster.submit(LaunchCluster.scala:81)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:188)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at scala.util.Try$.apply(Try.scala:191)
	at io.gearpump.util.AkkaApp$class.main(AkkaApp.scala:21)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:153)
	at io.gearpump.experiments.yarn.client.Client$.main(Client.scala:45)
	at io.gearpump.experiments.yarn.client.Client.main(Client.scala)
```

**Comment by clockfly** [comment]
Please reopen this if you confirmed there do exist a problem.
