### ISSUE TITLE
yarnclient launches gearpump application master with many exceptions and then hangs

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1741]
We should revert https://github.com/gearpump/gearpump/pull/1699 or correct the errors shown when launching gearpump by the yarnclient. Here is what is output:

```
$ output/target/pack/bin/yarnclient launch -package /user/gearpump/gearpump-pack-2.11.5-0.7.1-SNAPSHOT.zip -output /tmp/gp.conf
[INFO] [12/18/2015 19:37:49.169] [ClusterConfig$] loading config file application.conf...
[WARN] [12/18/2015 19:37:50.368] [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[WARN] [12/18/2015 19:37:50.398] [DomainSocketFactory] The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
[INFO] [12/18/2015 19:37:50.414] [RMProxy] Connecting to ResourceManager at cdh-master-0.node.demogotapaas.consul/10.10.10.146:8032
[INFO] [12/18/2015 19:37:50.541] [YarnClient] Starting YarnClient...
[INFO] [12/18/2015 19:37:50.857] [LaunchCluster] Starting AM
[INFO] [12/18/2015 19:37:51.221] [YarnClient] Create application, appId: application_1450294801051_3331
[INFO] [12/18/2015 19:37:51.222] [LaunchCluster] Uploading configuration files to remote HDFS(under hdfs://nameservice1/user/ec2-user/.gearpump_app3331/conf/)...
[INFO] [12/18/2015 19:37:51.669] [YarnClient] Submit Application application_1450294801051_3331 to YARN...
[INFO] [12/18/2015 19:37:51.696] [YarnClientImpl] Submitted application application_1450294801051_3331
[INFO] [12/18/2015 19:37:51.696] [LaunchCluster] Waiting application to finish...
......
[INFO] [12/18/2015 19:37:57.708] [LaunchCluster] Application application_1450294801051_3331 finished with state RUNNING at 0, info: 
================================================
==Application Id: application_1450294801051_3331
[INFO] [12/18/2015 19:37:57.760] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:57.761] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:57.761] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:57.762] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:57.762] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:57.762] [HttpMethodDirector] Retrying request
Failed to connect(tried 1)... Connection refused
[INFO] [12/18/2015 19:37:58.766] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:58.766] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:58.766] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:58.767] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:58.767] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:58.767] [HttpMethodDirector] Retrying request
Failed to connect(tried 2)... Connection refused
[INFO] [12/18/2015 19:37:59.770] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:59.770] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:59.770] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:59.771] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:37:59.771] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:37:59.771] [HttpMethodDirector] Retrying request
Failed to connect(tried 3)... Connection refused
[INFO] [12/18/2015 19:38:00.774] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:00.774] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:00.774] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:00.774] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:00.775] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:00.775] [HttpMethodDirector] Retrying request
Failed to connect(tried 4)... Connection refused
[INFO] [12/18/2015 19:38:01.778] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:01.778] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:01.779] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:01.779] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:01.779] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:01.779] [HttpMethodDirector] Retrying request
Failed to connect(tried 5)... Connection refused
[INFO] [12/18/2015 19:38:02.782] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:02.782] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:02.782] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:02.783] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:02.783] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:02.783] [HttpMethodDirector] Retrying request
Failed to connect(tried 6)... Connection refused
[INFO] [12/18/2015 19:38:03.786] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:03.786] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:03.787] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:03.787] [HttpMethodDirector] Retrying request
[INFO] [12/18/2015 19:38:03.787] [HttpMethodDirector] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
[INFO] [12/18/2015 19:38:03.787] [HttpMethodDirector] Retrying request
Failed to connect(tried 7)... Connection refused
[INFO] [12/18/2015 19:38:05.395] [launchCluster-akka.actor.default-dispatcher-4] [akka://launchCluster/deadLetters] Message [io.gearpump.experiments.yarn.appmaster.YarnAppMaster$GetActiveConfig] from Actor[akka://launchCluster/deadLetters] to Actor[akka://launchCluster/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

Help: 
-package (required:false, default:)<Please specify the gearpump.zip package path on HDFS. If not specified, we will use default value /user/gearpump/gearpump.zip>
-name (required:false, default:Gearpump)<Application name showed in YARN>
-verbose (required:false, default:false)<print verbose log on console>
-output (required:false, default:)<output path for configuration file>

Exception in thread "main" akka.pattern.AskTimeoutException: Recipient[Actor[akka://launchCluster/deadLetters]] had already been terminated.
	at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132)
	at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144)
	at io.gearpump.util.ActorUtil$.askActor(ActorUtil.scala:130)
	at io.gearpump.experiments.yarn.client.LaunchCluster.saveConfig(LaunchCluster.scala:102)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:190)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:22)
	at scala.util.Try$.apply(Try.scala:191)
	at io.gearpump.util.AkkaApp$class.main(AkkaApp.scala:21)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:151)
	at io.gearpump.experiments.yarn.client.Client$.main(Client.scala:45)
	at io.gearpump.experiments.yarn.client.Client.main(Client.scala)
```

Note that the gearpump application master was launched as well as the services. Additionally no output file was produced and only one worker was created. 
Note - Gearpump broker is expecting to see something like "masters=..." on the console after the yarnclient launches gearpump successfully. If this is no longer the case we should let @karol-brejna-i know.

**Comment by clockfly** [comment]
@kkasravi  Most error log lines you mentioned are expected, it will wait until the remote UI service is started. And the worker number can be configured at gear.conf.
@karol-brejna-i, @kkasravi , the yarn usage will be highlighted in release note of 0.7.1.

Looks like there is a bug about the configuration, will open a PR for this.

**Comment by clockfly** [comment]
PR #1745 fix this issue.
