### ISSUE TITLE
When upload application in UI, custom config file is not effective

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1772]

**Comment by darionyaphet** [comment]
I upload `examples/wordcount-2.11.5-0.7.0-assembly.jar` to gearpump 0.7 version in my machine .

It report a bug but the stream-process program is running . I don't know is it a bug or something wrong with me

**Comment by clockfly** [comment]
@darionyaphet


What is the phenomenon? Does the UI prompt error? What is the error message?

**Comment by darionyaphet** [comment]
I got some Error Message from ui.log , maybe useful . :)

```
2015-12-24 11:39:13,805 ERROR RestServices: Request to http://127.0.0.1:8090/api/v1.0/master/submitapp could not be handled normally
java.lang.NumberFormatException: For input string: "Application Id is 1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:247)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30)
	at io.gearpump.services.MasterService$.submitJar(MasterService.scala:229)
	at io.gearpump.services.MasterService$$anonfun$masterRoute$1$$anonfun$apply$2$$anonfun$apply$43$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$1.apply$mcI$sp(MasterService.scala:131)
	at io.gearpump.services.MasterService$$anonfun$masterRoute$1$$anonfun$apply$2$$anonfun$apply$43$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$1.apply(MasterService.scala:131)
	at io.gearpump.services.MasterService$$anonfun$masterRoute$1$$anonfun$apply$2$$anonfun$apply$43$$anonfun$apply$44$$anonfun$apply$45$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$1.apply(MasterService.scala:131)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by darionyaphet** [comment]
```
2015-12-24 11:39:11,332 ERROR redirect: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
```

Gearpump could support JDK 8 ?

**Comment by clockfly** [comment]
Yes, it supports JDK8, it is a warning, you can ignore it safely. 
"MaxPermSize" is a default option in gear.conf, you can remove that option.

**Comment by clockfly** [comment]
@darionyaphet 

About the UI error you saw, I think it was fixed at https://github.com/gearpump/gearpump/issues/1645
It is still on trunk. We plan to release 0.7.1 in the next few days.

**Comment by clockfly** [comment]
Create #1774 to track the MaxPermSize issue.

**Comment by stanleyxu2005** [comment]
The error message is addressed to an unknown issue.
```
2015-12-24 11:39:13,805 ERROR RestServices: Request to http://127.0.0.1:8090/api/v1.0/master/submitapp could not be handled normally
java.lang.NumberFormatException: For input string: "Application Id is 1"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
```

**Comment by stanleyxu2005** [comment]
The problem is The string is not the last line in output.

**Comment by clockfly** [comment]
Why need need to parse the console output?

**Comment by stanleyxu2005** [comment]
There are 2 cases:

1. When submit app via REST, we need an appid. 
2. When test submit app (incl. storm) from command line, we will parse output (not only appid)
