### ISSUE TITLE
ExecutorSystemLauncherSpec failed

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1819]
This seems not random since I've relaunched the master build several times.

```
[info] - should report timeout when trying to start a executor system on worker, and worker doesn't response *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (30 seconds) during expectMsgClass waiting for class io.gearpump.cluster.appmaster.ExecutorSystemLauncher$LaunchExecutorSystemTimeout
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:405)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
[info]   at io.gearpump.cluster.appmaster.ExecutorSystemLauncherSpec$$anonfun$3.apply$mcV$sp(ExecutorSystemLauncherSpec.scala:92)
[info]   at io.gearpump.cluster.appmaster.ExecutorSystemLauncherSpec$$anonfun$3.apply(ExecutorSystemLauncherSpec.scala:86)
[info]   at io.gearpump.cluster.appmaster.ExecutorSystemLauncherSpec$$anonfun$3.apply(ExecutorSystemLauncherSpec.scala:86)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

**Comment by clockfly** [comment]
fixedin PR#1818
