### ISSUE TITLE
Application fails after several days

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1848]
Reported by @karol-brejna-i 
Clicking on the application after several days results in (0.7.1-SNAPSHOT)

url: http://10.10.10.33:8099/api/v1.0/appmaster/1?detail=true
response:
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://app1-executor-1@cdh-worker-2.node.gotapaaseu.consul:48322/user/daemon/appdaemon1/$c#1399341787]] after [15000 ms]
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
    at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
    at java.lang.Thread.run(Thread.java:745)

**Comment by karol-brejna-i** [comment]
Restarting the app in the dashboard 'brings it to live' again.

**Comment by clockfly** [comment]
@karol-brejna-i 

Do you use it in YARN? When this happens? Can you attach all the logs? It will be helpful for us for troubleshooting.

**Comment by stanleyxu2005** [comment]
I previously created this issue #1577. It's the similar issue.

**Comment by karol-brejna-i** [comment]
I haven't reproduced this for a while now. I am thinking of closing the issue.

**Comment by kkasravi** [comment]
@karol-brejna-i  Agreed - i'm haven't been able to reproduce. However the instance at demo.gearpump.io no longer seems to be working. I see no errors in the browser console. @clockfly could you see what the server logs show?

**Comment by kkasravi** [comment]
Duplicate of #1577. Closing this issue.

**Comment by clockfly** [comment]
@kkasravi 

The demo instance have very small memory (1GB). I am checking it.
