### ISSUE TITLE
How to debug the UI dashboard in Intellij IDE

### ISSUE THREAD

**Issue by darionyaphet** [gearpump/gearpump#1950]
I running gearpump service in idea .Using admin account to login web UI and report a error message as following .

 I don't know it mean . Someone could help me ? thank you .

```
[INFO] [02/03/2016 00:05:28.424] [SecurityService@AUDIT] user admin login from 127.0.0.1:54400
[ERROR] [02/03/2016 00:05:28.425] [RestServices] Request to http://127.0.0.1:8090/login could not be handled normally
java.lang.ClassCastException: scala.scalajs.js.Object cannot be cast to scala.scalajs.js.Dictionary
	at scala.scalajs.js.Dictionary$.empty(Dictionary.scala:77)
	at scala.scalajs.js.Dictionary$.apply(Dictionary.scala:80)
	at upickle.json.package$.writeJs(package.scala:34)
	at upickle.json.package$.write(package.scala:38)
	at upickle.Types$class.write(Types.scala:125)
	at upickle.default$.write(Api.scala:25)
	at io.gearpump.services.SecurityService$$anonfun$io$gearpump$services$SecurityService$$login$1$$anonfun$apply$1.apply(SecurityService.scala:104)
	at io.gearpump.services.SecurityService$$anonfun$io$gearpump$services$SecurityService$$login$1$$anonfun$apply$1.apply(SecurityService.scala:101)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResult$1$$anonfun$apply$3.apply(BasicDirectives.scala:32)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResult$1$$anonfun$apply$3.apply(BasicDirectives.scala:32)
	at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1$$anonfun$1$$anonfun$apply$3$$anonfun$apply$4.apply(FutureDirectives.scala:61)
	at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1$$anonfun$1$$anonfun$apply$3$$anonfun$apply$4.apply(FutureDirectives.scala:61)
	at akka.http.scaladsl.util.FastFuture$.akka$http$scaladsl$util$FastFuture$$strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:51)
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:50)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by clockfly** [comment]
@darionyaphet 

Looks like there is some error in the dependency definition of IDE. Do you use Intellij?

From the error, the scalajs library (which is used for frontend javascript integration) jars was wrongly added to the backend service dependencies list.

**Comment by clockfly** [comment]
If you are using Intellij, please do the following check:

1. Open module settings -> choose project gearpump-serviceJVM -> check the Dependencies Tab -> Try to find artifact start with "com.lihaoyi".
If there are library like "upickle_sjs" or "derivesjs", it means the frontend scalajs jar was wrongly added to backend dependencies list.

**Comment by darionyaphet** [comment]
hi @clockfly thank you for you great help :)

I check the dependencies list and found `upickle_sjs ` and  `derivesjs ` jars . But when I restart service and access on my chrome browser it respond a text message .

```
The resource requires authentication, which was not supplied with the request
```

**Comment by clockfly** [comment]
@darionyaphet 

The error means we cannot find the static resource in classpath.

To debug the service in IDE, we need to add two extra classpath to classpath explicitly.
The first one is conf/ folder. 
The second one is services/dashboard folder 

Please try to add these folders to intellij module dependencies of project serviceJVM and see whether it works.

**Comment by clockfly** [comment]
@darionyaphet 

It will be much appreciated if you can contribute a patch to document your findings. Here is the related part in doc: https://github.com/gearpump/gearpump/blob/master/docs/dev-ide-setup.md

**Comment by clockfly** [comment]
```
[ERROR] [02/03/2016 12:32:23.258] [Util$] failed to read VERSION file, VERSION (No such file or directory)
I can't find the VERSION file ?
```
The VERSION file is resolved via a system property "gearpump.home". In shell scripts of release package, this environment system property is automatically set.

**Comment by darionyaphet** [comment]
@clockfly   Not only service , I think local maybe also add some config `MASTER` is undefined

**Comment by darionyaphet** [comment]
Hi  @clockfly I try to write a document about how to running and debugging Gearpump Service in Intellij IDEA . Could I put this document in `doc` ?

**Comment by clockfly** [comment]
Replaced by GEARPUMP-4.

**Comment by clockfly** [comment]
https://issues.apache.org/jira/browse/GEARPUMP-4
