### ISSUE TITLE
Document "Submit Your 1st Gearpump Application command" has not been updated?

### ISSUE THREAD

**Issue by kimutansk** [gearpump/gearpump#1961]
Hi, all.

Now I'm researching and trying gearpump.

In Gearpump document "Submit Your 1st Gearpump Application", command line is shown below.

```
### To run WordCount example
bin/gear app -jar examples/gearpump-examples-assembly-2.11-0.7.6.jar io.gearpump.streaming.examples.wordcount.WordCount
```

But when shown command line executed, below error was occured.
```
[ClusterConfig$] loading config file application.conf...
Warning: get unknown argument io.gearpump.streaming.examples.wordcount.WordCount, maybe it is a main class

Help: Submit an application to Master by providing a jar
-namePrefix (required:false, default:)<application name prefix>
-jar (required:true)<application>.jar
-verbose (required:false, default:false)<print verbose log on console>
-conf (required:false, default:)custom configuration file

Exception in thread "main" java.lang.Exception: jar examples/gearpump-examples-assembly-2.11-0.7.6.jar does not exist
        at io.gearpump.cluster.main.AppSubmitter$.main(AppSubmitter.scala:74)
        at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:25)
        at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:25)
        at scala.util.Try$.apply(Try.scala:191)
        at io.gearpump.util.AkkaApp$class.main(AkkaApp.scala:24)
        at io.gearpump.cluster.main.AppSubmitter$.main(AppSubmitter.scala:30)
        at io.gearpump.cluster.main.Gear$.executeCommand(Gear.scala:38)
        at io.gearpump.cluster.main.Gear$.main(Gear.scala:57)
        at io.gearpump.cluster.main.Gear.main(Gear.scala)
```

Next, I executed below command, submit succeeded.
```
bin/gear app -jar examples/wordcount-2.11-0.7.6-assembly.jar io.gearpump.streaming.examples.wordcount.WordCount
```

It seems like document has not been updated.
Can I send document fix PullRequest?

**Comment by kkasravi** [comment]
yes, please that would be great.

**Comment by huafengw** [comment]
Fixed
