### ISSUE TITLE
akka stream examples failed with ClassNotFoundException

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1980]
I launched a local cluster and ran akka stream examples with

```
output/target/pack/bin/gear app -jar experiments/akkastream/target/scala-2.11/akkastream-2.11.5-0.7.7-SNAPSHOT-assembly.jar akka.stream.gearpump.example.Test
```

Here is the stacktrace.
```
java.lang.ClassNotFoundException: akka.stream.gearpump.task.SourceBridgeTask
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at io.gearpump.streaming.executor.TaskLauncher.launch(TaskLauncher.scala:55)
        at io.gearpump.streaming.executor.Executor$$anonfun$dynamicDagPhase1$1.applyOrElse(Executor.scala:146)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at io.gearpump.streaming.executor.Executor.aroundReceive(Executor.scala:54)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kkasravi** [comment]
Hi @manuzhang Is this based on akka-stream-experimental 1.0?

**Comment by manuzhang** [comment]
@kkasravi yes. It's ok if I change `GraphCutter` to `AllLocalStrategy`

**Comment by manuzhang** [comment]
The executor of  `LocalCluster` shares the same classpath with worker, which doesn't include the client (akka stream) jar file

**Comment by huafengw** [comment]
Fixed by Sean
