### ISSUE TITLE
Add cross build and upgrade to akka 2.4.2 and off akka-stream-experimental

### ISSUE THREAD

**Issue by helena** [gearpump/gearpump#1988]

**Comment by helena** [comment]
Work started for PR.

**Comment by helena** [comment]
Looks like someone already is doing this.

**Comment by manuzhang** [comment]
@helena Thanks for your interests. You may like to give your comments on https://github.com/gearpump/gearpump/pull/1978. It's nice to have your ideas here.

**Comment by helena** [comment]
@manuzhang It is possible to still do this with a cross build, if anyone would like me to proceed and get this upgrade done.

**Comment by kkasravi** [comment]
Hi @helena - sure a cross build would be great. I made some pretty simple changes in the current Build.scala. I can always merge your contribution. So for all of gearpump we should do 2.3.14. For the experiments/akkastream we should do 2.4.2. According to akka's 2.4.2 documentation - it's backward compatible with 2.3.X.

**Comment by manuzhang** [comment]
@kam could you create a branch based on your PR such that @helena and others could make changes to it ?

**Comment by kkasravi** [comment]
sure - https://github.com/gearpump/gearpump/tree/akka-stream

**Comment by helena** [comment]
Thanks all :)

**Comment by helena** [comment]
Starting work on this now.

**Comment by helena** [comment]
Shall I re-open this ticket to PR against or do we want a new one?

**Comment by kkasravi** [comment]
thanks @helena !

**Comment by clockfly** [comment]
@helena 

I am not sure you have started on this or not. There is some tricky part that are error-prone, so I did a try in implementing this. If you already have some code, maybe we can try to combine them. 

My branch is at: https://github.com/clockfly/gearpump/tree/issue_1988_2

Currently, I am still facing some compatibility problems. There are some strange akka-http error log like this:
```
2016-03-25 09:11:41,266 INFO Slf4jLogger: Slf4jLogger started
2016-03-25 09:11:41,461 INFO Remoting: Starting remoting
2016-03-25 09:11:42,139 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://services@127.0.0.1:61956]
2016-03-25 09:11:42,224 INFO Metrics$: Metrics is enabled...,  true
2016-03-25 09:11:42,265 INFO MasterProxy@masterproxyservices: Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
2016-03-25 09:11:42,271 INFO MasterProxy@masterproxyservices: Master Proxy is started...
2016-03-25 09:11:42,280 INFO MasterProxy@masterproxyservices: sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:3000/), Path(/user/master)]
2016-03-25 09:11:42,315 INFO MasterProxy@masterproxy104767894: Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
2016-03-25 09:11:42,315 INFO MasterProxy@masterproxy104767894: Master Proxy is started...
2016-03-25 09:11:42,315 INFO MasterProxy@masterproxy104767894: sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:3000/), Path(/user/master)]
2016-03-25 09:11:43,550 INFO MasterProxy@masterproxy104767894: Connected to [akka.tcp://master@127.0.0.1:3000/user/master]
2016-03-25 09:11:43,551 INFO MasterProxy@masterproxyservices: Connected to [akka.tcp://master@127.0.0.1:3000/user/master]
2016-03-25 09:11:45,878 INFO Services$: Please browse to http://127.0.0.1:8090 to see the web UI
2016-03-25 09:12:00,443 INFO SecurityService@AUDIT: user admin login from 127.0.0.1:61988
2016-03-25 09:12:01,156 WARN Serialization(akka://services): Using the default Java serializer for class [io.gearpump.cluster.AppMasterToMaster$GetMasterData$] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
2016-03-25 09:12:01,951 WARN Serialization(akka://services): Using the default Java serializer for class [io.gearpump.cluster.ClientToMaster$QueryHistoryMetrics] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
2016-03-25 09:12:13,820 WARN Serialization(akka://services): Using the default Java serializer for class [io.gearpump.cluster.MasterToAppMaster$AppMastersDataRequest$] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
2016-03-25 09:13:01,893 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
2016-03-25 09:13:01,913 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
2016-03-25 09:13:04,172 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
2016-03-25 09:13:04,212 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
2016-03-25 09:13:04,252 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
2016-03-25 09:13:46,168 INFO Util$: Starting executor process java io.gearpump.cluster.main.AppSubmitter -jar C:\Users\xzhong10\AppData\Local\Temp\userfile_jar_8758569692106823279complexdag-2.11-0.7.6-assembly.jar; options: -Dgearpump.home=C:\myData\gearpump\output\target\pack\bin\.. -Dgearpump.hostname=127.0.0.1 -Djava.net.preferIPv4Stack=true -Dgearpump.cluster.masters.0=127.0.0.1:3000
2016-03-25 09:13:51,372 INFO redirect: [ClusterConfig$] loading config file application.conf...
2016-03-25 09:13:52,081 INFO redirect: [ClusterConfig$] loading config file application.conf...
2016-03-25 09:13:55,205 INFO redirect: [Slf4jLogger] Slf4jLogger started
2016-03-25 09:13:56,445 INFO redirect: [Remoting] Starting remoting
2016-03-25 09:13:57,209 INFO redirect: [Remoting] Remoting started; listening on addresses :[akka.tcp://client740459667@127.0.0.1:49632]
2016-03-25 09:13:57,288 INFO redirect: [Metrics$] Metrics is enabled...,  true
2016-03-25 09:13:57,291 INFO redirect: [ClientContext] Starting system client740459667
2016-03-25 09:13:57,340 INFO redirect: [MasterProxy@masterproxy156504615] Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
2016-03-25 09:13:57,345 INFO redirect: [MasterProxy@masterproxy156504615] sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:3000/), Path(/user/master)]
2016-03-25 09:13:57,345 INFO redirect: [MasterProxy@masterproxy156504615] Master Proxy is started...
2016-03-25 09:13:57,844 INFO redirect: [MasterProxy@masterproxy156504615] Connected to [akka.tcp://master@127.0.0.1:3000/user/master]
2016-03-25 09:13:58,017 INFO redirect: [ClientContext] Creating master proxy Actor[akka://client740459667/user/masterproxyclient740459667#2030721558] for master list: List(HostPort(127.0.0.1,3000))
2016-03-25 09:13:58,036 INFO redirect: [MasterProxy@masterproxyclient740459667] Contacts point URL: akka.tcp://master@127.0.0.1:3000/user/master
2016-03-25 09:13:58,036 INFO redirect: [MasterProxy@masterproxyclient740459667] Master Proxy is started...
2016-03-25 09:13:58,036 INFO redirect: [MasterProxy@masterproxyclient740459667] sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:3000/), Path(/user/master)]
2016-03-25 09:13:58,045 INFO redirect: [Serialization(akka://client740459667)] Using the default Java serializer for class [io.gearpump.cluster.ClientToMaster$GetJarStoreServer$] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
2016-03-25 09:13:58,059 INFO redirect: [MasterProxy@masterproxyclient740459667] Connected to [akka.tcp://master@127.0.0.1:3000/user/master]
2016-03-25 09:14:01,620 INFO redirect: [Serialization(akka://client740459667)] Using the default Java serializer for class [io.gearpump.cluster.ClientToMaster$SubmitApplication] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
2016-03-25 09:14:06,190 INFO redirect: Submit application succeed. The application id is 1
2016-03-25 09:14:06,190 INFO redirect: [ClientContext] Shutting down system client740459667
2016-03-25 09:14:06,244 INFO redirect: [RemoteActorRefProvider$RemotingTerminator] Shutting down remote daemon.
2016-03-25 09:14:06,257 INFO redirect: [RemoteActorRefProvider$RemotingTerminator] Remote daemon shut down; proceeding with flushing remote transports.
2016-03-25 09:14:06,593 ERROR redirect: Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
2016-03-25 09:14:06,807 ERROR RepointableActorRef: Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$RequestTimeoutSupport@31f16a10]: requirement failed: Cannot push port (responseOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (responseOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:439)
	at akka.http.impl.engine.server.HttpServerBluePrint$RequestTimeoutSupport$$anon$6$$anon$9.onPush(HttpServerBluePrint.scala:292)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:582)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:593)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:443)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:398)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:493)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-03-25 09:16:02,191 ERROR RepointableActorRef: Error in stage [recover]: No elements passed in the last 1 minute.
akka.http.impl.engine.HttpConnectionTimeoutException: No elements passed in the last 1 minute.
```

**Comment by clockfly** [comment]
The problem above is probably solved by https://github.com/akka/akka/issues/18982#issuecomment-160931684

Will raise a PR now.
