### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.gearpump.util.RecreateRollingFileAppender

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#2098]
```
log4j:ERROR Could not instantiate class [org.apache.gearpump.util.RecreateRollingFileAppender].
java.lang.ClassNotFoundException: org.apache.gearpump.util.RecreateRollingFileAppender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
	at io.gearpump.util.LogUtil$.loadConfiguration(LogUtil.scala:85)
	at io.gearpump.util.MasterClientCommand$class.main(MasterClientCommand.scala:32)
	at io.gearpump.cluster.main.Local$.main(Local.scala:36)
	at io.gearpump.cluster.main.Local.main(Local.scala)
log4j:ERROR Could not instantiate appender named "RollingFileAppender".
```

**Comment by manuzhang** [comment]
Fixed in #2100
